import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Header from "./components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <aside className="fixed top-0 left-0 h-screen w-[20vw] bg-white shadow-md z-40">
          <Sidebar />
        </aside>
        <header className="fixed top-0 left-[20vw] w-[80vw] h-[76px] bg-white shadow z-50">
          <Header />
        </header>
        <main className="ml-[20vw] mt-[76px] w-[79vw] p-5 bg-gray-100 min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
